ci_service: travis_ci
coverage_service: coveralls
workspace: SearchingTechniques.xcodeworkspace
xcodeproj: SearchingTechniques.xcodeproj
scheme: SearchingTechniques
source_directory: SearchingTechniques/