language: objective-c
osx_image: xcode8.3

env:
  global:
  - LC_CTYPE=en_US.UTF-8
  - LANG=en_US.UTF-8
  - WORKSPACE=SearchingTechniques.xcworkspace
  - IOS_FRAMEWORK_SCHEME="SearchingTechniques-iOS"
  - MACOS_FRAMEWORK_SCHEME="SearchingTechniques-macOS"
  - TVOS_FRAMEWORK_SCHEME="SearchingTechniques-tvOS"
  - IOS_SDK=iphonesimulator10.3
  - MACOS_SDK=macosx10.12
  - TVOS_SDK=appletvsimulator10.2
  - RUN_TESTS="YES"
  - POD_LINT="NO"
  matrix:
    - DESTINATION="OS=10.3.1,name=iPhone SE" SCHEME="$IOS_FRAMEWORK_SCHEME" SDK="$IOS_SDK"
    - DESTINATION="OS=9.0,name=iPhone 6" SCHEME="$IOS_FRAMEWORK_SCHEME" SDK="$IOS_SDK"
    - DESTINATION="arch=x86_64" SCHEME="$MACOS_FRAMEWORK_SCHEME" SDK="$MACOS_SDK"
    - DESTINATION="OS=10.0,name=Apple TV 1080p" SCHEME="$TVOS_FRAMEWORK_SCHEME" SDK="$TVOS_SDK"
    - DESTINATION="OS=9.0,name=Apple TV 1080p" SCHEME="$TVOS_FRAMEWORK_SCHEME" SDK="$TVOS_SDK"

before_install:
- rm -rf /Users/travis/Library/Developer/Xcode/DerivedData/SearchingTechniques-*/
- rvm use $RVM_RUBY_VERSION

install:
- bundle install

script:
  - set -o pipefail
  - xcodebuild -version
  - xcodebuild -showsdks

# Build in Debug and Run Tests if specified
  - if [ $RUN_TESTS == "YES" ]; then
      travis_retry xcodebuild -workspace "$WORKSPACE" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=YES ENABLE_TESTABILITY=YES test | xcpretty;
    else
      xcodebuild -workspace "$WORKSPACE" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=YES build | xcpretty;
    fi

after_success: slather